### PR TITLE
fix(controls): restore form state when querystring is incomplete

### LINKED ISSUE #22: Make url parameters optional
When you only set the `url` parameter in the url it breaks. Shall we make all url parameters optional?

### PR DESCRIPTION
**Pull request by reinoute**
Resolves #22

### CODE REVIEW

**Comment by decrek** [comment]
When only having one(or two) querystring parameters and changing the missing one(s) the url does not update.

File: src/assets/a11y-viewer.js [hunk 1]
```diff
@@ -60,17 +60,33 @@
...
     function restoreForm(state) {
 
-        formElements.forEach(function (element) {
-            var newValue = state[element.id];
-
-            if (element.type == "checkbox" && element.checked.toString() != newValue) {
+        for (var key in state) {
+            var element = formElements.filter(function (element) {
+                return element.id == key;
+            })[0];
```
Comment (decrek) [inline src/assets/a11y-viewer.js]: I think this is more clear:

``` js
var element = formElements.forEach(function (element) {
    if (element.id == key) {
        return element;
    }
});
```

File: src/assets/a11y-viewer.js [hunk 2]
```diff
@@ -60,17 +60,33 @@
...
+            var newValue = state[key];
+
+            if (!element) {
+                return false;
+            } else if (element.type == 'checkbox') {
                 element.checked = newValue == "true";
                 update(element, false);
-            } else if (element.value != newValue) {
+            } else if (element.type == 'select-one'){
+                var isValidOption = arrayFrom(element.options).some(function (option) {
```
Comment (decrek) [inline src/assets/a11y-viewer.js]: this whole else if can be replaced with:

``` js
var options = arrayFrom(element.options);
for (var i=0; i<options; i++) {
    if (options[i].value === newValue) {
        element.value = newValue;
        update(element, false);
        break;
    }
}
```

I think this is more clear

File: src/assets/a11y-viewer.js [hunk 3]
```diff
@@ -1,169 +1,136 @@
...
-
-        visionSelectOptions.forEach(function (option) {
-            main.classList.remove(option.value);
-        });
-
-        main.classList.add(value);
+    // Update the address bar with input/values excluding the submit button
+    function updateUrl() {
+        // Only update the URL when the history API is supported
+        if ('pushState' in window.history) {
```
Comment (decrek) [inline src/assets/a11y-viewer.js]: I believe this check is not necessary since `is_capable_browser` in `index.html` depends on `classList` and `css filters`?

File: src/assets/a11y-viewer.js [hunk 4]
```diff
@@ -1,169 +1,136 @@
...
+            // Exclude the submit button
+            var inputs = arrayFrom(FORM.elements).filter(function (element) {
```
Comment (decrek) [inline src/assets/a11y-viewer.js]: shall we remove the arrayfrom function and just use `Array.prototype.filter.call` instead? or map, reduce, foreach, etc
